
[all:vars]
# SSH Connection Settings
ansible_connection=ssh
ansible_port=22
ansible_user=ansible
ansible_password={{ vault_password }}
ansible_python_interpreter=/usr/bin/python3
ansible_pipelining=True

# Sudo Settings
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root

[db_servers]

# Development Servers
dev-db-01 ansible_host=IP_ADDRESS db_instance="INSTANCE_NAME" server_role="dev"
dev-db-02 ansible_host=IP_ADDRESS db_instance="INSTANCE_NAME" server_role="dev"


[db_servers:vars]
# Biến riêng cho group db_servers
ansible_become=true
ansible_become_user=root

[dev]
dev-db-01
dev-db-02

[staging]
staging-db-01
staging-db-02

[production]
prod-db-01
prod-db-02
prod-db-03

[dev:vars]
environment=dev
remediation_enabled=true
audit_schedule="0 3 * * *"
log_level=DEBUG
send_report_email=false

[staging:vars]
environment=staging
remediation_enabled=false
audit_schedule="0 2 * * *"
log_level=INFO
send_report_email=true

[production:vars]
environment=production
remediation_enabled=false
audit_schedule="0 2 * * *"
log_level=INFO
send_report_email=true
alerting_enabled=true

[primary_servers]
prod-db-01

[secondary_servers]
prod-db-02

[replica_servers]
prod-db-03
