---
# Biến cụ thể cho môi trường DEV
environment: dev
remediation_enabled: true  # Cho phép remediation trong DEV
audit_schedule: "0 3 * * *"  # Chạy 3h sáng
log_level: "DEBUG"
send_report_email: false

db_hosts:
  - host: localhost
    port: 1433
    instance: "SQLEXPRESS01"
    audit_credentials_vault: "vault_dev_audit_db_user"
    remediation_credentials_vault: "vault_dev_remediation_db_user"

monitoring_enabled: false
